name: Self Service Deployment

on:
  workflow_dispatch:
    inputs:
      use_generative:
        description: 'Use Generative AI for Dockerfile (fallback only)'
        required: true
        default: 'true'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      USE_GENERATIVE: ${{ github.event.inputs.use_generative }}

    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v3

    - name: Clone Docker Templates Repo
      run: |
        git clone https://github.com/gsaksham963/docker-templates.git docker-templates

    - name: Detect Framework via find
      run: |
        if FIND_PATH=$(find . -name "pom.xml" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Java Spring Boot" >> $GITHUB_ENV
          echo "PORT=8080" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        elif FIND_PATH=$(find . -name "package.json" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Node.js" >> $GITHUB_ENV
          echo "PORT=3000" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        elif FIND_PATH=$(find . -name "angular.json" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Angular" >> $GITHUB_ENV
          echo "PORT=4200" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        elif FIND_PATH=$(find . -name "vue.config.js" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Vue.js" >> $GITHUB_ENV
          echo "PORT=8080" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        elif FIND_PATH=$(find . -name "manage.py" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Django" >> $GITHUB_ENV
          echo "PORT=8000" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        elif FIND_PATH=$(find . -name "app.py" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Flask" >> $GITHUB_ENV
          echo "PORT=5000" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        elif FIND_PATH=$(find . -name "main.go" -print -quit) && [ -n "$FIND_PATH" ]; then
          echo "FRAMEWORK=Go" >> $GITHUB_ENV
          echo "PORT=8080" >> $GITHUB_ENV
          echo "ENTRY_PATH=$FIND_PATH" >> $GITHUB_ENV
        else
          echo "FRAMEWORK=Unknown" >> $GITHUB_ENV
          echo "PORT=3000" >> $GITHUB_ENV
          echo "ENTRY_PATH=." >> $GITHUB_ENV
        fi

    - name: Try Using Predefined Dockerfile Template
      id: template_check
      run: |
        case "$FRAMEWORK" in
          "Java Spring Boot") TEMPLATE="docker-templates/springboot.Dockerfile" ;;
          "Node.js") TEMPLATE="docker-templates/node.Dockerfile" ;;
          "Angular") TEMPLATE="docker-templates/angular.Dockerfile" ;;
          "Vue.js") TEMPLATE="docker-templates/vue.Dockerfile" ;;
          "Django") TEMPLATE="docker-templates/django.Dockerfile" ;;
          "Flask") TEMPLATE="docker-templates/flask.Dockerfile" ;;
          "Go") TEMPLATE="docker-templates/go.Dockerfile" ;;
          ".NET") TEMPLATE="docker-templates/dotnet.Dockerfile" ;;
          *) TEMPLATE="" ;;
        esac

        if [ -n "$TEMPLATE" ] && [ -f "$TEMPLATE" ]; then
          cp "$TEMPLATE" Dockerfile
          echo "TEMPLATE_FOUND=true" >> $GITHUB_ENV
          cat Dockerfile
        else
          echo "TEMPLATE_FOUND=false" >> $GITHUB_ENV
        fi

    - name: Package Framework Metadata
      if: env.TEMPLATE_FOUND == 'false' && env.USE_GENERATIVE == 'true'
      run: |
        echo "{\"request\": \"Generate a Dockerfile only\", \"framework\": \"$FRAMEWORK\", \"port\": $PORT, \"entry_path\": \"$ENTRY_PATH\"}" > docker_prompt.json
        cat docker_prompt.json

    - name: Generate Dockerfile with Groq API
      if: env.TEMPLATE_FOUND == 'false' && env.USE_GENERATIVE == 'true'
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        PROMPT=$(cat docker_prompt.json | jq -Rs .)
        jq -n --arg prompt "$PROMPT" '{
          model: "meta-llama/llama-4-scout-17b-16e-instruct",
          messages: [{role: "user", content: $prompt}]
        }' > payload.json

        curl https://api.groq.com/openai/v1/chat/completions -s \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -d @payload.json \
          -o docker.json

    - name: Extract Dockerfile from Groq Response
      if: env.TEMPLATE_FOUND == 'false' && env.USE_GENERATIVE == 'true'
      run: |
        jq -r '.choices[0].message.content' docker.json | \
          sed -n '/```dockerfile/,/```/p' | \
          sed '1d;$d' > Dockerfile
        echo "Extracted Dockerfile:"
        cat Dockerfile

    - name: Final Check for Dockerfile
      run: |
        if [ ! -f Dockerfile ]; then
          echo "Dockerfile not found. Exiting."
          exit 1
        fi
