name: Deploy to AWS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
        include:
          - os: macos-latest
            node: 18
          - os: ubuntu-latest
            node: 14
    steps:
      - name: Run echo command
        run: |
          echo "OS: ${{matrix.os}}"
          echo "Node: ${{matrix.node}}"
